name: flutter_mapbox_autocomplete
description: A Flutter Package for MapBox Places autocomplete
version: 0.0.2
homepage: https://github.com/lhamycodes/flutter_mapbox_autocomplete

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
